### ISSUE TITLE
Episode 0

### ISSUE THREAD

**Issue by satoshun** [op-urd/podcast#1]
- 録音(ソフトウェアとか)をどうするか

**Comment by ymizushi** [comment]
# 水島が話したいこと
* Rustについて
    * Go -> Rust
    * Java -> Rustでの違いとか。

**Comment by satoshun** [comment]
TEST

**Comment by satoshun** [comment]
## さとしゅんが話したいこと

- Kotlinについて
  - Javaと比較したときのKotlin

**Comment by ymizushi** [comment]
# テーマ
* ジェネリクス
* ガベージコレクション
* 関数型プログラミング

**Comment by ymizushi** [comment]
> 録音

普通に 付属の GarageBandで録音、ぐらいを考えていた。
機材とかは、不足があれば追加していく感じが良いかなーと。

**Comment by nabetama** [comment]
# podcast について

##  録音環境
静かなところがいい。自宅でMBPのマイクそのまま使ってAudacityで録音してみたけど夜なら全然大丈夫だった. skypeでも平気じゃないかな。ただ、キーボードノイズけっこう拾ってたのが気になる。

  - [ ] いつものところ
  - [ ] 誰かの自宅
  - [ ] Skypeでリモート

## 録音
garagebandは使ったこと無いから知らない。audacityは↑で使ってみた。

  - [ ] garageband
  - [ ] audacity

## ホスティング方法
  - [ ] github pages + 静的サイトジェネレータ(Jykyll, hugoとか)
  - [ ] VPSとかで自前でつくる（だるそう.やらなそう）

##  https化
  - [ ] route53
  - [ ] Let's Encrypt(podcastが許してくれるのかは不明)

## キャッシュサーバー
  - [ ] [Cloudflare](https://www.cloudflare.com/)とか？

## ドメイン
  - [ ] githubでホスティングしたとして、github.ioのままやる（できるのかな？）
  - [ ] ドメイン取る(fmドメインは10k円くらいする。urd.fmは空いてたｗ)

## nabetamaが話したいこと

- 転職
- COMP
- リモートワークについて

**Comment by nabetama** [comment]
終わってるしcloseしても良さそう

**Comment by ymizushi** [comment]
クローズしますか。

**Comment by ymizushi** [comment]
クローズしました。
