### ISSUE TITLE
8/24 みずたま勉強会 Podcastの第1回テーマを決める

### ISSUE THREAD

**Issue by ymizushi** [op-urd/podcast#2]
# 概要

Podcastのテーマを決める

**Comment by ymizushi** [comment]
# 水島案

一般的な話だけど、「プログラミングの上達テクニック」をテーマに話したい。

プログラミングを上達するために意識すること、習慣化していること、何から学ぶべきかなど。

**Comment by nabetama** [comment]
みんなこのへんどう思ってるのかなって気になった

サブトピ[「今年は…何か大きめのOSSにコントリビュートしたいですね」
](https://medium.com/@timakin/%E4%BB%8A%E5%B9%B4%E3%81%AF-%E4%BD%95%E3%81%8B%E5%A4%A7%E3%81%8D%E3%82%81%E3%81%AEoss%E3%81%AB%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AA%E3%83%93%E3%83%A5%E3%83%BC%E3%83%88%E3%81%97%E3%81%9F%E3%81%84%E3%81%A7%E3%81%99%E3%81%AD-902771f0ba0e)

サブトピ[ticwatch 買った](https://www.kickstarter.com/projects/mobvoi/ticwatch-s-and-e-a-truly-optimized-smartwatch)

**Comment by satoshun** [comment]
サブトピ: Google Wifi良さ?

**Comment by ymizushi** [comment]
# プログラミングの上達テクニック

## 楽しむ



## 興味のある分野から学習する

## 基本的なCSの知識を優先する

## 設計プロセスとコーディングプロセスを明確に分ける

## 失敗を振り返る

## よく読んでよく書く

## ドキュメント

### 一次ドキュメントを参照する癖をつける

## コーディング

### テストを書く

### デバッガーを使う

### デバッガーやIDEに頼りすぎない

### エラーやウォーニングをしっかり読む

**Comment by ymizushi** [comment]
無事終わったのでクローズします
