### ISSUE TITLE
ポッドキャストのロゴを用意する

### ISSUE THREAD

**Issue by ymizushi** [op-urd/podcast#4]

**Comment by ymizushi** [comment]
![2017-09-09 22 16 52](https://user-images.githubusercontent.com/788785/30240512-abaa3814-95ac-11e7-8332-df5915fa5e48.png)

ロゴ案１

**Comment by ymizushi** [comment]
ロゴ案2

![onlinelogomaker-090917-2228-5925](https://user-images.githubusercontent.com/788785/30240599-53830ba0-95ae-11e7-90f8-214627056823.png)

**Comment by nabetama** [comment]
2

**Comment by ymizushi** [comment]
何個か作ってコンペ方式でやってみようかと。

**Comment by satoshun** [comment]
2かな

**Comment by nabetama** [comment]
@ymizushi の圧倒的才能の前にひれ伏すしかない
